version: '2'
services:
    crowdware-app:
        image: crowdware
        external_links:
            - crowdware-mysql:mysql
            - crowdware-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/crowdware?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    crowdware-mysql:
        extends:
            file: mysql.yml
            service: crowdware-mysql
    crowdware-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: crowdware-elasticsearch
